# Generated by Django 3.0 on 2020-01-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Player', models.CharField(max_length=32)),
                ('G', models.IntegerField()),
                ('GS', models.IntegerField()),
                ('MP', models.DecimalField(decimal_places=1, max_digits=3)),
                ('FG', models.DecimalField(decimal_places=1, max_digits=3)),
                ('FGA', models.DecimalField(decimal_places=1, max_digits=3)),
                ('eFG', models.DecimalField(decimal_places=3, max_digits=4)),
                ('TRB', models.DecimalField(decimal_places=1, max_digits=3)),
                ('AST', models.DecimalField(decimal_places=1, max_digits=3)),
                ('STL', models.DecimalField(decimal_places=1, max_digits=3)),
                ('BLK', models.DecimalField(decimal_places=1, max_digits=3)),
                ('PF', models.DecimalField(decimal_places=1, max_digits=2)),
                ('PTS', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Prediction', models.BooleanField()),
                ('Actual', models.BooleanField()),
            ],
        ),
    ]
