# Generated by Django 3.0 on 2020-01-08 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualAllStars',
            fields=[
                ('Player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='finder.PlayerStats')),
            ],
            options={
                'verbose_name_plural': 'PlayerStats',
            },
        ),
        migrations.CreateModel(
            name='PredictedAllStars',
            fields=[
                ('Player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='finder.PlayerStats')),
            ],
            options={
                'verbose_name_plural': 'PlayerStats',
            },
        ),
        migrations.AlterModelOptions(
            name='playerstats',
            options={'verbose_name_plural': 'PlayerStats'},
        ),
    ]
