# Generated by Django 3.0 on 2020-01-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20200107_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualallstars',
            options={'verbose_name_plural': 'ActualAllStars'},
        ),
        migrations.AlterModelOptions(
            name='predictedallstars',
            options={'verbose_name_plural': 'PredictedAllStars'},
        ),
    ]
